import { jsonrepair } from 'jsonrepair';
import TinyAiInstance2 from '../TinyAiInstance2.mjs';
import errorCodes from '../utils/errorCodes.mjs';

/**
 * Configures the Tiny AI Api to use the Google Gemini API.
 *
 * This function sets up the Google Gemini API in a TinyAiInstance2, translating
 * the internal OpenAI-like structure into Gemini's specific 'parts' and 'inlineData' format.
 *
 * @param {TinyAiInstance2} tinyGoogleAI - The TinyAiApi instance to be configured.
 * @param {string} GEMINI_API_KEY - The API key for Google Gemini.
 * @param {string} [MODEL_DATA='gemini-2.0-flash'] - The model to use.
 */
export function setTinyGoogleAi(tinyGoogleAI, GEMINI_API_KEY, MODEL_DATA = 'gemini-2.0-flash') {
  const apiUrl = 'https://generativelanguage.googleapis.com/v1beta';
  tinyGoogleAI.setApiKey(GEMINI_API_KEY);
  tinyGoogleAI.setModel(MODEL_DATA);

  /**
   * Registers a predefined set of error codes and their associated messages for interpreting
   * the finish reasons returned by the Google Generative AI API.
   *
   * Each error code maps to a human-readable explanation and optional display rules (e.g. `hide`).
   * These can be used to provide meaningful messages in the UI or logs when handling model responses.
   *
   * @function
   * @name tinyGoogleAI._setErrorCodes
   * @param {Object<string, {text: string, hide?: boolean}>} errorCodes - An object where each key is an error/finish reason returned by the API,
   * and the value contains a `text` message and optionally a `hide` flag to control visibility in UI.
   *
   * @returns {void}
   *
   * @example
   * tinyGoogleAI._setErrorCodes({
   *   STOP: { text: 'Natural stop point of the model or provided stop sequence.', hide: true },
   *   MAX_TOKENS: { text: 'The maximum number of tokens as specified in the request was reached.' },
   *   SAFETY: { text: 'The response candidate content was flagged for safety reasons.' },
   *   ...
   * });
   *
   * Example usage:
   * const reason = response.finishReason;
   * const errorInfo = tinyGoogleAI.getErrorCode(reason);
   * console.log(errorInfo.text); // Shows friendly explanation for the finish reason
   */
  tinyGoogleAI._setErrorCodes({
    FINISH_REASON_UNSPECIFIED: { text: 'Default value. This value is unused.' },
    STOP: { text: 'Natural stop point of the model or provided stop sequence.', hide: true },
    MAX_TOKENS: { text: 'The maximum number of tokens as specified in the request was reached.' },
    SAFETY: { text: 'The response candidate content was flagged for safety reasons.' },
    RECITATION: { text: 'The response candidate content was flagged for recitation reasons.' },
    LANGUAGE: {
      text: 'The response candidate content was flagged for using an unsupported language.',
    },
    OTHER: { text: 'Unknown reason.' },
    BLOCKLIST: { text: 'Token generation stopped because the content contains forbidden terms.' },
    PROHIBITED_CONTENT: {
      text: 'Token generation stopped for potentially containing prohibited content.',
    },
    SPII: {
      text: 'Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).',
    },
    MALFORMED_FUNCTION_CALL: { text: 'The function call generated by the model is invalid.' },
    IMAGE_SAFETY: {
      text: 'Token generation stopped because generated images contain safety violations.',
    },
  });

  /**
   * @param {*} [result={ error: { code: null, message: null, status: null, details: null } }]
   * @param {*} [finalData={ error: { code: null, message: null, status: null, details: null } }]
   */
  const buildErrorData = (result = { error: {} }, finalData = {}) => {
    finalData.error = {
      code: typeof result.error?.code === 'number' ? result.error.code : null,
      message: typeof result.error?.message === 'string' ? result.error.message : null,
      status: typeof result.error?.status === 'string' ? result.error.status : null,
      details: result.error?.details || null,
    };
  };

  /**
   * @typedef {Object<any, any>} ObjectAny
   */

  /**
   * Translates TinyAiInstance2 internal format into Gemini Request format.
   * Extracts base64 correctly for vision capability support.
   *
   * @param {Array<ObjectAny>} data - Internal conversation history.
   * @param {ObjectAny} [config={}] - Model configuration.
   * @param {ObjectAny|null} [cache=null] - Cached content configuration.
   * @param {boolean} [cacheMode=false] - Whether it is running in cache mode.
   * @returns {ObjectAny} Formatted request payload for Gemini.
   */
  const requestBuilder = (data, config = {}, cache = null, cacheMode = false) => {
    /**
     * @type {{
     * safetySettings: {};
     * model: any;
     * ttl: any;
     * name: any;
     * contents: Array<any>;
     * systemInstruction: any;
     * generationConfig: {
     *    maxOutputTokens: any;
     *    temperature: any;
     *    topP: any;
     *    topK: any;
     *    presencePenalty: any;
     *    frequencyPenalty: any;
     *    enableEnhancedCivicAnswers: any;
     * };
     *  cachedContent: any;
     * }}
     */
    const requestBody = {};
    if (!cacheMode) requestBody.safetySettings = [];
    // Model
    if (typeof config.model === 'string') requestBody.model = config.model;
    // Expiration
    if (typeof config.ttl === 'string') requestBody.ttl = config.ttl;
    // Expiration
    if (typeof config.name === 'string') requestBody.name = config.name;

    // Execute builder
    for (const item of data) {
      if (!item) continue;

      const role = item.role === 'assistant' ? 'model' : item.role === 'system' ? 'system' : 'user';
      const parts = [];

      if (typeof item.content === 'string') {
        parts.push({ text: item.content });
      } else if (Array.isArray(item.content)) {
        for (const part of item.content) {
          if (part.type === 'text') parts.push({ text: part.text });
          else if (part.type === 'image_url' && part.image_url?.url) {
            const match = part.image_url.url.match(/^data:(.+);base64,(.+)$/);
            if (match) parts.push({ inlineData: { mimeType: match[1], data: match[2] } });
          }
        }
      }

      if (role === 'system') {
        if (!requestBody.systemInstruction) requestBody.systemInstruction = { parts: [] };
        requestBody.systemInstruction.parts.push(...parts);
      } else {
        if (!requestBody.contents) requestBody.contents = [];
        requestBody.contents.push({ role, parts });
      }
    }

    // Config
    if (!cacheMode) {
      // @ts-ignore
      requestBody.generationConfig = {};
      /**
       * @param {number|null} val
       * @param {string} key
       */
      const setIfNumber = (val, key) => {
        // @ts-ignore
        if (typeof val === 'number') requestBody.generationConfig[key] = val;
      };

      setIfNumber(tinyGoogleAI.getMaxOutputTokens(), 'maxOutputTokens');
      setIfNumber(tinyGoogleAI.getTemperature(), 'temperature');
      setIfNumber(tinyGoogleAI.getTopP(), 'topP');
      setIfNumber(tinyGoogleAI.getTopK(), 'topK');
      setIfNumber(tinyGoogleAI.getPresencePenalty(), 'presencePenalty');
      setIfNumber(tinyGoogleAI.getFrequencyPenalty(), 'frequencyPenalty');
    }

    // Cache
    if (cache) requestBody.cachedContent = cache;
    // Complete
    return requestBody;
  };

  // https://ai.google.dev/api/generate-content?hl=pt-br#method:-models.generatecontent
  /**
   * Internal method that integrates with Google Gemini via generateContent or streamGenerateContent.
   * It builds the request body, handles normal and streaming responses, parses tokens and content,
   * and returns structured response data.
   *
   * @function
   * @name tinyGoogleAI._setGenContent
   * @param {string} apiKey - Your Google AI API key.
   * @param {boolean} isStream - Whether the request is a streaming request.
   * @param {object[]} data - An array of messages to send (prompt).
   * @param {string} model - The Gemini model ID (e.g., "gemini-pro").
   * @param {Function} streamingCallback - Callback for streaming results. Called with partials.
   * @param {AbortController} controller - Optional abort controller for cancelling requests.
   * @returns {Promise<object>} finalData - A promise that resolves with a structured response object:
   * - finalData.contents: Parsed content output
   * - finalData.tokenUsage: Usage info with prompt/candidate/total counts
   * - finalData.modelVersion: Model version string
   * - finalData._response: Raw response
   * - finalData.error: (If error occurred) contains message, status, and code
   */
  tinyGoogleAI._setGenContent(
    /**
     * @param {string} apiKey
     * @param {boolean} isStream
     * @param {any} data
     * @param {string} model
     * @param {function} streamingCallback
     * @param {AbortController} controller
     * @returns {any}
     */
    (apiKey, isStream, data, model, streamingCallback, controller) =>
      new Promise((resolve, reject) => {
        // Request
        const requestBody = requestBuilder(data);

        /**
         * Parses token usage metadata from the result object.
         *
         * @param {*} result - The API response containing usageMetadata.
         * @returns {[object, boolean]} Tuple of metadata object and whether an error occurred.
         * @private
         */
        const buildUsageMetada = (result) => {
          const usageMetadata = { count: { candidates: null, prompt: null, total: null } };
          if (result.usageMetadata) {
            // Candidates
            usageMetadata.count.candidates = result.usageMetadata.candidatesTokenCount ?? null;
            // Prompt
            usageMetadata.count.prompt = result.usageMetadata.promptTokenCount ?? null;
            // Total
            usageMetadata.count.total = result.usageMetadata.totalTokenCount ?? null;
            return [usageMetadata, false];
          }
          return [usageMetadata, true];
        };

        /**
         * Parses the Gemini response format back into the TinyAiInstance2 format.
         *
         * @param {*} result - The result object from the API response.
         * @param {*} finalData - The object where content candidates are appended.
         * @private
         */
        const buildContent = (result, finalData) => {
          if (!Array.isArray(result.candidates)) return;
          for (const item of result.candidates) {
            if (item.content) {
              // Finished reason
              const finishReason =
                typeof item.finishReason === 'string' ? item.finishReason.toUpperCase() : undefined;
              // Build content
              const role = item.content.role === 'model' ? 'assistant' : 'user';
              let textContent = '';

              if (Array.isArray(item.content.parts)) {
                for (const part of item.content.parts) {
                  if (part.text) textContent += part.text;
                }
              }
              finalData.contents.push({ role, content: textContent, finishReason });
            }
          }
        };

        /**
         * Final handler that transforms the result into a structured response.
         *
         * @param {*} result - The response from the Gemini API.
         * @returns {*} finalData - Structured result with content, usage, model version, or error.
         * @private
         */
        const finalPromise = (result) => {
          // Prepare final data
          /** @type {*} */
          const finalData = { _response: result };
          if (!result.error) {
            // Content
            finalData.contents = [];

            // Model Version
            finalData.modelVersion =
              typeof result.modelVersion === 'string' ? result.modelVersion : null;

            // Token Usage
            const [tokenUsage, needShowMetadataError] = buildUsageMetada(result);
            finalData.tokenUsage = tokenUsage;
            if (needShowMetadataError) {
              console.error('[Google API] Usage Metadata not found.');
              console.log(result);
            }

            // Build content
            buildContent(result, finalData);
          }

          // Error result
          else buildErrorData(result, finalData);

          // Complete
          return finalData;
        };

        /**
         * Handles streaming Gemini response via Fetch and TextDecoder.
         * Buffers content and sends back partials using the streamingCallback.
         *
         * @async
         * @param {ReadableStream} stream - The ReadableStream from fetch().body
         * @returns {Promise<void>}
         * @private
         */
        const streamingResponse = async (stream) => {
          try {
            const reader = stream.getReader();
            const decoder = new TextDecoder('utf-8');
            let done = false;
            let countData = 0;
            let streamResult = {};
            const streamCache = [];

            // Read streaming
            console.groupCollapsed('[google-generative] Streaming request.');
            console.log(`[ai-config] [${model}]`, requestBody, data);
            while (!done) {
              const { value, done: streamDone } = await reader.read();
              done = streamDone;
              if (value) {
                const chunk = decoder.decode(value, { stream: true });
                if (!done) {
                  try {
                    let cleanedJson = chunk.trim();
                    if (cleanedJson.startsWith(',')) cleanedJson = cleanedJson.substring(1);
                    if (cleanedJson.length > 1) {
                      cleanedJson = jsonrepair(cleanedJson);
                      cleanedJson = `${!cleanedJson.startsWith('[') ? '[' : ''}${cleanedJson}${!cleanedJson.endsWith(']') ? ']' : ''}`;
                      const jsonChunk = JSON.parse(cleanedJson);

                      console.log(`[${countData}]`, chunk);
                      console.log(`[${countData}]`, cleanedJson);
                      console.log(`[${countData}]`, jsonChunk);

                      // Send temp data
                      for (const result of jsonChunk) {
                        if (result) {
                          /** @type {*} */
                          const tinyData = { contents: [] };
                          buildContent(result, tinyData);

                          for (let i = 0; i < tinyData.contents.length; i++) {
                            if (!streamCache[i])
                              streamCache[i] = { content: '', role: tinyData.contents[i].role };
                            streamCache[i].content += tinyData.contents[i].content || '';
                            tinyData.contents[i].content = streamCache[i].content;
                          }

                          streamResult = result;
                          streamingCallback({
                            tokenUsage: buildUsageMetada(result)[0],
                            contents: tinyData.contents,
                            done: false,
                          });
                        }
                      }
                    }
                  } catch (err) {
                    console.warn('[Google API] Stream parsing warning on chunk.');
                  }
                }
              }
              countData++;
            }
            console.groupEnd();

            // Complete
            streamingCallback({ done: true });
            const finalData = finalPromise(streamResult);
            for (let i = 0; i < finalData.contents.length; i++) {
              if (streamCache[i]) finalData.contents[i].content = streamCache[i].content;
            }
            resolve(finalData);
          } catch (err) {
            reject(err);
          }
        };

        // Request
        const fetchRequest = fetch(
          `${apiUrl}/models/${model}:${!isStream ? 'generateContent' : 'streamGenerateContent'}?key=${encodeURIComponent(apiKey)}`,
          {
            signal: controller?.signal,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(requestBody),
          },
        );

        // Request
        fetchRequest
          .then((res) => {
            // Normal
            if (!isStream)
              res
                .json()
                .then((result) => resolve(finalPromise(result)))
                .catch(reject);
            else {
              // Error Streaming
              if (!res.body) reject(new Error('No AI streaming value found.'));
              else if (!res.ok)
                reject(
                  new Error(
                    `Error HTTP ${res.status}: ${res.statusText || errorCodes[res.status] || 'Unknown'}`,
                  ),
                );
              // Streaming
              else streamingResponse(res.body);
            }
          })
          // Error
          .catch(reject);
      }),
  );

  // https://ai.google.dev/api/models?hl=pt_br#method:-models.list
  /**
   * Registers a function to fetch and organize the list of available Google AI models.
   * The returned models are grouped into categories (`main`, `exp`, `others`) and sorted based on a predefined versioning logic.
   *
   * @function
   * @name tinyGoogleAI._setGetModels
   * @param {function(string, number, string=): Promise<Object>} callback - A function that takes an API key, an optional page size, and an optional page token,
   * and returns a Promise with the processed models data.
   *
   * @returns {void}
   *
   * @example
   * tinyGoogleAI._setGetModels((apiKey, pageSize, pageToken) => { ... });
   *
   * Returned object when resolved:
   * {
   *   _response: <original API response>,
   *   newData: [<processed and inserted model objects>]
   * }
   *
   * Model structure inserted into `tinyGoogleAI`:
   * {
   *   _response: <original model>,
   *   category: { displayName, id, index },
   *   index: <number>,
   *   name: <string>,
   *   id: <string>,
   *   displayName: <string>,
   *   version: <string>,
   *   description: <string>,
   *   inputTokenLimit: <number>,
   *   outputTokenLimit: <number>,
   *   temperature: <number>,
   *   topP: <number>,
   *   topK: <number>,
   *   supportedGenerationMethods: [<string>]
   * }
   */
  tinyGoogleAI._setGetModels(
    /**
     * @param {string} apiKey
     * @param {number} pageSize
     * @param {string} pageToken
     * @returns {any}
     */
    (apiKey, pageSize, pageToken) =>
      new Promise((resolve, reject) =>
        fetch(
          `${apiUrl}/models?key=${encodeURIComponent(apiKey)}&pageSize=${pageSize}${pageToken ? `&pageToken=${pageToken}` : ''}`,
          {
            method: 'GET',
            headers: { 'Content-Type': 'application/json' },
          },
        )
          // Request
          .then((res) => res.json())
          .then((result) => {
            // Prepare final data
            /** @type {*} */
            const finalData = { _response: result };
            if (!result.error) {
              finalData.newData = [];

              // Update Token
              tinyGoogleAI._setNextModelsPageToken(result.nextPageToken);

              let mIndex = -1;
              for (const item of result.models) {
                mIndex++;
                if (item.supportedGenerationMethods?.includes('generateContent')) {
                  const inserted = tinyGoogleAI._insertNewModel({
                    _response: item,
                    index: mIndex,
                    name: item.name,
                    id: item.name.substring(7),
                    displayName: item.displayName,
                    version: item.version,
                    description: item.description,
                    inputTokenLimit: item.inputTokenLimit,
                    outputTokenLimit: item.outputTokenLimit,
                    temperature: item.temperature,
                    topP: item.topP,
                    topK: item.topK,
                    supportedGenerationMethods: item.supportedGenerationMethods,
                  });
                  if (inserted) finalData.newData.push(inserted);
                }
              }
            }

            // Error result
            else buildErrorData(result, finalData);

            // Complete
            resolve(finalData);
          })
          // Error
          .catch(reject),
      ),
  );

  // https://ai.google.dev/api/tokens?hl=pt-br#method:-models.counttokens
  /**
   * Registers a function to calculate token usage for a given model and input data using Google AI's `countTokens` endpoint.
   *
   * @function
   * @name tinyGoogleAI._setCountTokens
   * @param {function(string, string, AbortController?, Object): Promise<Object>} callback - A function that takes an API key, model ID,
   * an optional AbortController, and the input data for the token count request. Returns a Promise with token count information.
   *
   * @returns {void}
   *
   * @example
   * tinyGoogleAI._setCountTokens((apiKey, model, controller, data) => { ... });
   *
   * Returned object when resolved:
   * {
   *   _response: <original API response>,
   *   totalTokens: <number|null>,
   *   cachedContentTokenCount: <number|null>,
   *   promptTokensDetails: {
   *     tokenCount: <number|null>,
   *     modality: <string|null>
   *   }
   * }
   */
  tinyGoogleAI._setCountTokens(
    /**
     * @param {string} apiKey
     * @param {string} model
     * @param {AbortController} controller
     * @param {any} data
     * @returns {any}
     */
    (apiKey, model, controller, data) =>
      new Promise((resolve, reject) => {
        const dataContent = requestBuilder(data);
        const modelInfo = tinyGoogleAI.getModelData(model);
        dataContent.model = modelInfo?.name;

        if (dataContent.contents?.length > 0) {
          fetch(`${apiUrl}/models/${model}:countTokens?key=${encodeURIComponent(apiKey)}`, {
            signal: controller?.signal,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ generateContentRequest: dataContent }),
          })
            // Request
            .then((res) => res.json())
            .then((result) => {
              /** @type {*} */
              const finalData = { _response: result };
              if (!result.error) {
                // Total tokens
                if (typeof result.totalTokens === 'number')
                  finalData.totalTokens = result.totalTokens;
                else finalData.totalTokens = null;

                // Cached Content Token Count
                if (typeof result.cachedContentTokenCount === 'number')
                  finalData.cachedContentTokenCount = result.cachedContentTokenCount;
                else finalData.cachedContentTokenCount = null;
              }
              // Error result
              else buildErrorData(result, finalData);
              // Complete
              resolve(finalData);
            })
            // Error
            .catch(reject);
        } else resolve({ _response: {}, totalTokens: null, cachedContentTokenCount: null });
      }),
  );

  // Complete
  return tinyGoogleAI;
}

/**
 * Creates and configures a new TinyAiInstance2 that is set up with the Google Gemini API.
 *
 * @class
 * @extends TinyAiInstance2
 * @param {string} GEMINI_API_KEY - The API key used to authenticate with the Google Gemini API.
 * @param {string} [MODEL_DATA='gemini-2.0-flash'] - Optional. The model identifier to use. Defaults to `'gemini-2.0-flash'`.
 * @param {boolean} [isSingle=false] - If true, configures the instance to handle a single session only.
 * @returns {TinyAiInstance2} A configured instance of TinyAiApi.
 */
class TinyGoogleAi extends TinyAiInstance2 {
  constructor(GEMINI_API_KEY = '', MODEL_DATA = 'gemini-2.0-flash', isSingle = false) {
    super(isSingle);
    setTinyGoogleAi(this, GEMINI_API_KEY, MODEL_DATA);
  }
}

export { TinyGoogleAi };
